In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('AdventureWork_name_employee.csv',sep=",",names= ['id','name'])

In [14]:
df.head(5)

id       name
0   1    Gustavo
1   2  Catherine
2   3        Kim
3   4   Humberto
4   5      Pilar

In [15]:
list_reader=df['id'].tolist()

In [16]:
type(list_reader)

list

In [23]:
from random import shuffle

In [24]:
def randomUniqueList(number,listData):
    ex=[]
    for i in range (0,number):
        shuffle(listData)  #re-arrange order of memeber in the list
        mylist2 = listData
        dax=mylist2.pop()  #select random member in unique fashion
        ex.append(dax)
    return ex
        

In [36]:
employeeId=randomUniqueList(12,list_reader)

In [217]:
# Generate list of number plus1 every member of list
def GenerateListSerial(start,number):  
    listValue=[] 
    start=start-1
    for i in range (0,number):
        start=start+1
        listValue.append(start)
    return listValue

In [31]:
# Generate list of constant number  eg. year 
def GenerateConstantList(constant,number):
    listValue=[]
    for i in range(0,number):
        listValue.append(constant)
    return listValue

In [32]:
copNo1=GenerateConstantList(1,12)

In [35]:
year2011=GenerateConstantList(2011,12)

## import numpy as np
df1 = np.random.randint(1, 6, df1.20)

# or if the numbers are non-consecutive (albeit slower)
df1 = np.random.choice([1, 9, 20], 20)

In [253]:
a_del = np.delete(a, 1, 0)
print(a_del)
# [[ 0  1  2  3]
#  [ 8  9 10 11]]



[ 0  2  3  4  5  6  7  8  9 10 11]


In [256]:
a_del = np.delete(a, 3, 0)
print(a_del)

[ 0  1  2  4  5  6  7  8  9 10 11]


In [260]:
a_del = np.delete(a_del, 0, 0)
print(a_del)

[ 5  6  7  8  9 10 11]


In [2]:
a =[1,2,3,4]
b =['a','b','c','d']

In [37]:
# Calling DataFrame constructor after zipping 
# both lists, with columns specified 
df = pd.DataFrame(list(zip(year2011,copNo1,employeeId)), 
               columns =['Year', 'CopNo','EmployeeId'])

In [38]:
df

Year  CopNo  EmployeeId
0   2011      1         431
1   2011      1         810
2   2011      1          62
3   2011      1         835
4   2011      1         622
5   2011      1         786
6   2011      1         821
7   2011      1         845
8   2011      1          20
9   2011      1         849
10  2011      1         541
11  2011      1         994