In [39]:
import numpy as np
import pandas as pd

In [2]:
ef = np.array([1,66,45])

In [3]:
sum(ef)

112

In [4]:
ge=[2,4,5,2]
gr=np.array(ge)

In [5]:
gr

array([2, 4, 5, 2])

In [16]:
np.max(gr)

5

In [17]:
np.min(gr)

2

In [7]:
min(gr)

2

In [15]:
np.mean(gr)

3.25

In [18]:
max(ge)

5

In [24]:
np.mean(ge)

3.25

In [25]:
a = np.arange(12)**2 

In [26]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [30]:
 i = np.array( [ 1,2,3,8,5 ] ) 

In [31]:
i

array([1, 2, 3, 8, 5])

In [32]:
a[i]  

array([ 1,  4,  9, 64, 25])

In [37]:
index=[1,4]
a[index]

array([ 1, 16])

In [57]:
data=[[1,2,3,4],[5,6,7,8]]
index=['a','b']
column=['w','x','y','z']

In [58]:
df=pd.DataFrame(data,index,column)

In [59]:
df

w  x  y  z
a  1  2  3  4
b  5  6  7  8

In [60]:
df.index

Index(['a', 'b'], dtype='object')

In [61]:
len(df.index)

2

In [62]:
type(df.index)

pandas.indexes.base.Index

In [63]:
for fd in df.index:
    print(fd)

a
b


In [65]:
df.values

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int64)

In [69]:
df.values[1]

array([5, 6, 7, 8], dtype=int64)

In [67]:
df.columns

Index(['w', 'x', 'y', 'z'], dtype='object')

In [68]:
df.columns[1]

'x'

In [70]:
df

w  x  y  z
a  1  2  3  4
b  5  6  7  8

In [71]:
df.loc['a':]

w    1
x    2
y    3
z    4
Name: a, dtype: int64

In [72]:
ef=df.loc['a']

In [77]:
ef.T

w    1
x    2
y    3
z    4
Name: a, dtype: int64

In [82]:
# Select  from row a-b  and columns w,z,x 
df.loc['a':'b',['w','z','x']]

w  z  x
a  1  4  2
b  5  8  6